on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  backport:
    runs-on: ubuntu-latest
    env:
      CONTEXT: ${{ toJson(github.event) }}
    steps:
      - run: |
          echo "$CONTEXT"
