on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  backport:
    # Only run this job if the triggering workflow was not skipped (and on grafana repo)
    if: github.event.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.head.repo.fork }}"
      - run: echo "${{ github.repository }}"
      - run: echo "Do something important"
