on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  backport:
    if: github.event.workflow_run.head_repository.fork == false
    runs-on: ubuntu-latest
    env:
      CONTEXT: ${{ toJson(github.event) }}
    steps:
      - run: |
          echo "$CONTEXT"
