on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.head.repo.fork }}"
      - run: echo "${{ github.repository }}"
      - run: echo "Do something important"
