on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
jobs:
  backport:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "PR number: ${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "PR head repo: ${{ github.event.workflow_run.pull_requests[0].head.repo.full_name }}"
          echo "Is fork?: ${{ github.event.workflow_run.pull_requests[0].head.repo.fork }}"
